# Generated by Django 4.1.1 on 2022-09-12 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jop', '0006_jop_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='jop',
            name='image',
            field=models.ImageField(default='', upload_to='jops/'),
            preserve_default=False,
        ),
    ]
