# Generated by Django 4.1.1 on 2022-09-13 17:33

from django.db import migrations, models
import jop.models


class Migration(migrations.Migration):

    dependencies = [
        ('jop', '0007_jop_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='jop',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jop',
            name='image',
            field=models.ImageField(upload_to=jop.models.image_upload),
        ),
    ]
